# HTML Headers and Footers Module
# This module provides header and footer functions for HTML reports
# Author: Refactored from json_to_html.R

# Define null coalescing operator
`%||%` <- function(x, y) if (is.null(x)) y else x

#' Create Simple Header
#'
#' @param title Report title
#' @param num_assertions Number of assertions
#' @param num_pmids Number of PMIDs
#' @return HTML header string
#' @export
create_simple_header <- function(title, num_assertions, num_pmids) {
    header <- paste0(
        "<div class='header'>",
        "<h1>", title, "</h1>",
        "</div>"
    )
    return(header)
}

#' Create HTML Header Section
#' 
#' @param title Report title
#' @param num_assertions Number of assertions
#' @param num_pmids Number of PMIDs
#' @return HTML header string
#' @export
create_html_header <- function(title, num_assertions, num_pmids) {
    header <- paste0(
        "<div class='container'>",
        "<div class='header'>",
        "<h1>", title, "</h1>",
        "<div class='meta'>",
        "<p>", num_assertions, " Causal Assertions | ", num_pmids, " Publications</p>",
        "</div>",
        "</div>"
    )
    return(header)
}

#' Create Enhanced Header
#'
#' @param title Report title
#' @param num_assertions Number of assertions
#' @param num_pmids Number of PMIDs
#' @return HTML header string
#' @export
create_enhanced_header <- function(title, num_assertions, num_pmids) {
    header <- paste0(
        "<div class='header'>",
        "<h1>", title, "</h1>",
        "<p>", num_assertions, " Causal Assertions | ", num_pmids, " Publications</p>",
        "</div>"
    )
    return(header)
}

#' Create Optimized Head Section
#'
#' @param title Report title
#' @param total_assertions Total number of assertions
#' @param enable_search Enable search functionality
#' @return HTML head content
#' @export
create_optimized_head <- function(title, total_assertions, enable_search = TRUE) {
    head_content <- paste0(
        "<head>",
        "<meta charset='UTF-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        "<title>", title, "</title>",
        "</head>"
    )
    return(head_content)
}

#' Create Empty HTML Report
#'
#' @param title Report title
#' @return Complete HTML string for empty report
#' @export
create_empty_html_report <- function(title) {
    html <- paste(
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        "<meta charset='UTF-8'>",
        "<title>", title, "</title>",
        "<style>",
        "body { font-family: Arial, sans-serif; padding: 40px; text-align: center; }",
        ".message { background-color: #f8f9fa; padding: 30px; border-radius: 8px; ",
        "border: 1px solid #dee2e6; max-width: 600px; margin: 0 auto; }",
        "h1 { color: #007bff; }",
        "p { color: #666; }",
        "</style>",
        "</head>",
        "<body>",
        "<div class='message'>",
        "<h1>", title, "</h1>",
        "<p>No data available to display.</p>",
        "<p>The report contains no causal assertions or PMID sentences.</p>",
        "</div>",
        "</body>",
        "</html>",
        sep = "\n"
    )
    return(html)
}

#' Create Simple Footer
#'
#' @return HTML footer string
#' @export
create_simple_footer <- function() {
    footer <- paste0(
        "<div class='footer'>",
        "<p><strong>CausalKnowledgeTrace</strong> - Evidence Report</p>",
        "</div>"
    )
    return(footer)
}

#' Create HTML Footer
#'
#' @return HTML footer string
#' @export
create_html_footer <- function() {
    footer <- paste0(
        "<div class='footer'>",
        "<p>Generated by <strong>CausalKnowledgeTrace</strong></p>",
        "<p>Causal Evidence Report | ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "</p>",
        "</div>",
        "</div>", # Close container
        "</body>",
        "</html>"
    )
    return(footer)
}

#' Create Enhanced Footer
#'
#' @param total_assertions Total number of assertions
#' @return HTML footer string
#' @export
create_enhanced_footer <- function(total_assertions) {
    footer <- paste0(
        "<div class='footer'>",
        "<p>Generated by <strong>CausalKnowledgeTrace</strong> | ",
        format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "</p>",
        "<p>Total Assertions: ", total_assertions, "</p>",
        "</div>"
    )
    return(footer)
}

