# List of R packages to install in new environment
# Generated from current R installation
# Run this script to install all required packages

required_packages <- c(
  "brew",
  "brio", 
  "commonmark",
  "credentials",
  "crosstalk",
  "curl",
  "dagitty",
  "desc",
  "devtools",
  "diffobj",
  "downlit",
  "dplyr",
  "DT",
  "ellipsis",
  "gert",
  "gh",
  "gitcreds",
  "httpuv",
  "httr2",
  "ini",
  "later",
  "lazyeval",
  "miniUI",
  "openssl",
  "pkgbuild",
  "pkgdown",
  "pkgload",
  "praise",
  "profvis",
  "promises",
  "ragg",
  "rcmdcheck",
  "remotes",
  "roxygen2",
  "rprojroot",
  "rversions",
  "SEMgraph",
  "sessioninfo",
  "shiny",
  "shinyBS",
  "shinydashboard",
  "shinyjs",
  "sourcetools",
  "systemfonts",
  "testthat",
  "textshaping",
  "urlchecker",
  "usethis",
  "visNetwork",
  "waldo",
  "whisker",
  "xml2",
  "xopen",
  "xtable",
  "zip",
  "abind",
  "askpass",
  "aspect",
  "backports",
  "base64enc",
  "BH",
  "Biobase",
  "BiocGenerics",
  "BiocManager",
  "BiocParallel",
  "BiocVersion",
  "bit",
  "bit64",
  "bitops",
  "blob",
  "broom",
  "bslib",
  "cachem",
  "callr",
  "caTools",
  "cellranger",
  "cherry",
  "cli",
  "clipr",
  "colorspace",
  "conflicted",
  "corpcor",
  "cpp11",
  "crayon",
  "cvAUC",
  "data.table",
  "DBI",
  "dbplyr",
  "digest",
  "dtplyr",
  "e1071",
  "evaluate",
  "fansi",
  "farver",
  "fastmap",
  "filelock",
  "flip",
  "fontawesome",
  "forcats",
  "foreach",
  "formatR",
  "fs",
  "futile.logger",
  "futile.options",
  "gam",
  "gdata",
  "generics",
  "GenomeInfoDbData",
  "ggm",
  "ggplot2",
  "glasso",
  "glmnet",
  "glue",
  "gplots",
  "graph",
  "gtable",
  "gtools",
  "haven",
  "highr",
  "hms",
  "hommel",
  "htmltools",
  "htmlwidgets",
  "igraph",
  "isoband",
  "iterators",
  "jquerylib",
  "jsonlite",
  "knitr",
  "labeling",
  "lambda.r",
  "lavaan",
  "lifecycle",
  "lpSolve",
  "lubridate",
  "magrittr",
  "MatrixGenerics",
  "matrixStats",
  "memoise",
  "mime",
  "mnormt",
  "modelr",
  "munsell",
  "mvtnorm",
  "nnls",
  "numDeriv",
  "pbapply",
  "pbivnorm",
  "pillar",
  "pkgconfig",
  "plogr",
  "plyr",
  "png",
  "prettyunits",
  "processx",
  "progress",
  "protoclust",
  "proxy",
  "ps",
  "purrr",
  "quadprog",
  "R6",
  "rappdirs",
  "RBGL",
  "RColorBrewer",
  "Rcpp",
  "RcppEigen",
  "RCurl",
  "readr",
  "readxl",
  "rematch",
  "rematch2",
  "reprex",
  "Rgraphviz",
  "rjson",
  "rlang",
  "rmarkdown",
  "ROCR",
  "RSQLite",
  "rstudioapi",
  "sass",
  "scales",
  "selectr",
  "shape",
  "snow",
  "someMTP",
  "stringi",
  "stringr",
  "SuperLearner",
  "sys",
  "tibble",
  "tidyr",
  "tidyselect",
  "timechange",
  "tinytex",
  "tmle",
  "tzdb",
  "utf8",
  "uuid",
  "V8",
  "vctrs",
  "viridisLite",
  "vroom",
  "withr",
  "xfun",
  "yaml",
  "zlibbioc"
)

# Function to install missing packages
install_missing_packages <- function() {
  # Get currently installed packages
  installed <- rownames(installed.packages())
  
  # Find packages that are not yet installed
  missing <- setdiff(required_packages, installed)
  
  if (length(missing) > 0) {
    cat("Installing", length(missing), "missing packages:\n")
    cat(paste(missing, collapse = ", "), "\n\n")
    
    # Install missing packages
    install.packages(missing, dependencies = TRUE)
    
    cat("Installation complete!\n")
  } else {
    cat("All packages are already installed.\n")
  }
}

# Run the installation
install_missing_packages()

# Optional: Load commonly used packages
# library(dplyr)
# library(ggplot2)
# library(tidyr)
# library(readr)