-- Assuming causalentity table already exists in public schema with structure:
-- public.causalentity (cui, name, semtype) where semtype contains comma-separated values

-- Drop tables if they exist (for clean reinstall)
-- DROP TABLE IF EXISTS filtered.cui_search;
DROP TABLE IF EXISTS filtered.semantic_types;

-- Create the semantic types reference table in filtered schema
CREATE TABLE filtered.semantic_types (
    semtype VARCHAR(10) PRIMARY KEY,
    semtype_definition VARCHAR(250) NOT NULL
);

-- Insert semantic type definitions
INSERT INTO filtered.semantic_types (semtype, semtype_definition) VALUES
('aapp', 'Amino Acid | Peptide | Protein'),
('acab', 'Acquired Abnormality'),
('acty', 'Activity'),
('aggp', 'Age Group'),
('alga', 'Algae'),
('amas', 'Amino Acid Sequence'),
('amph', 'Amphibian'),
('anab', 'Anatomical Abnormality'),
('anim', 'Animal'),
('anst', 'Anatomical Structure'),
('antb', 'Antibiotic'),
('arch', 'Archaeon'),
('bacs', 'Biologically Active Substance'),
('bact', 'Bacterium'),
('bdsu', 'Body Substance'),
('bdsy', 'Body System'),
('bhvr', 'Behavior'),
('biof', 'Biologic Function'),
('bird', 'Bird'),
('blor', 'Body Location or Region'),
('bmod', 'Biomedical Occupation or Discipline'),
('bodm', 'Biomedical or Dental Material'),
('bpoc', 'Body Part | Organ | Organ Component'),
('bsoj', 'Body Space or Junction'),
('carb', 'Carbohydrates'),
('celc', 'Cell Component'),
('celf', 'Cell Function'),
('cell', 'Cell'),
('cgab', 'Congenital Abnormality'),
('chem', 'Chemical'),
('chvf', 'Chemical Viewed Functionally'),
('chvs', 'Chemical Viewed Structurally'),
('clas', 'Classification'),
('clna', 'Clinical Attribute'),
('clnd', 'Clinical Drug'),
('cnce', 'Conceptual Entity'),
('comd', 'Cell or Molecular Dysfunction'),
('crbs', 'Carbohydrate Sequence'),
('diap', 'Diagnostic Procedure'),
('dora', 'Daily or Recreational Activity'),
('drdd', 'Drug Delivery Device'),
('dsyn', 'Disease or Syndrome'),
('edac', 'Educational Activity'),
('eehu', 'Environmental Effect of Humans'),
('eico', 'Eicosapentaenoic Compound'),
('elii', 'Element | Ion | Isotope'),
('emod', 'Experimental Model of Disease'),
('emst', 'Embryonic Structure'),
('enty', 'Entity'),
('enzy', 'Enzyme'),
('euka', 'Eukaryote'),
('evnt', 'Event'),
('famg', 'Family Group'),
('ffas', 'Fully Formed Anatomical Structure'),
('fish', 'Fish'),
('fndg', 'Finding'),
('fngs', 'Fungus'),
('food', 'Food'),
('ftcn', 'Functional Concept'),
('genf', 'Genetic Function'),
('geoa', 'Geographic Area'),
('gngm', 'Gene or Genome'),
('gora', 'Governmental or Regulatory Activity'),
('grpa', 'Group Attribute'),
('grup', 'Group'),
('hcpp', 'Human-caused Phenomenon or Process'),
('hcro', 'Health Care Related Organization'),
('hlca', 'Health Care Activity'),
('hops', 'Hazardous or Poisonous Substance'),
('horm', 'Hormone'),
('humn', 'Human'),
('idcn', 'Idea or Concept'),
('imft', 'Immunologic Factor'),
('inbe', 'Individual Behavior'),
('inch', 'Inorganic Chemical'),
('inpo', 'Injury or Poisoning'),
('inpr', 'Intellectual Product'),
('invt', 'Invertebrate Vector Host'),
('irda', 'Indicator | Reagent | Diagnostic Aid'),
('lang', 'Language'),
('lbpr', 'Laboratory Procedure'),
('lbtr', 'Laboratory or Test Result'),
('lipd', 'Lipids'),
('mamm', 'Mammal'),
('mbrt', 'Molecular Biology Research Technique'),
('mcha', 'Machine Activity'),
('medd', 'Medical Device'),
('menp', 'Mental Process'),
('mnob', 'Manufactured Object'),
('mobd', 'Mental or Behavioral Dysfunction'),
('moft', 'Molecular Function'),
('mosq', 'Molecular Sequence'),
('neop', 'Neoplastic Process'),
('nnon', 'Nucleic Acid | Nucleoside | Nucleotide'),
('npop', 'Natural Phenomenon or Process'),
('nsba', 'Non-specific Biogenic Amines'),
('nusq', 'Nucleotide Sequence'),
('ocac', 'Occupational Activity'),
('ocdi', 'Occupation or Discipline'),
('opco', 'Organophosphoryl Compound'),
('orch', 'Organic Chemical'),
('orga', 'Organism Attribute'),
('orgf', 'Organism Function'),
('orgm', 'Organism'),
('orgt', 'Organization'),
('ortf', 'Organ or Tissue Function'),
('patf', 'Pathologic Function'),
('phob', 'Physical Object'),
('phpr', 'Phenomenon or Process'),
('phsf', 'Physiologic Function'),
('phsu', 'Pharmacologic Substance'),
('plnt', 'Plant'),
('podg', 'Patient or Disabled Group'),
('popg', 'Population Group'),
('prog', 'Professional or Occupational Group'),
('pros', 'Professional Society'),
('qlco', 'Qualitative Concept'),
('qnco', 'Quantitative Concept'),
('rcpt', 'Receptor'),
('rept', 'Reptile'),
('resa', 'Research Activity'),
('resd', 'Research Device'),
('rich', 'Rickettsia-like Coxiella Homologue'),
('rnlw', 'Regulation or Law'),
('sbst', 'Substance'),
('shro', 'Self-help or Relief Organization'),
('socb', 'Social Behavior'),
('sosy', 'Sign or Symptom'),
('spco', 'Spatial Concept'),
('strd', 'Steroids'),
('tisu', 'Tissue'),
('tmco', 'Temporal Concept'),
('topp', 'Therapeutic or Preventive Procedure'),
('virs', 'Virus'),
('vita', 'Vitamin'),
('vtbt', 'Vertebrate');
